export const LOAD_COURSES = 'LOAD_COURSES';
export const LOAD_BEST_COURSES = 'LOAD_BEST_COURSES';
export const LOAD_INSTRUCTORS = 'LOAD_INSTRUCTORS';
export const LOAD_BEST_INSTRUCTORS = 'LOAD_BEST_INSTRUCTORS';
